#!/usr/bin/env ruby
#
# This scripts modifies the citation markup in HTML generated by pandoc
# and pandoc-citeproc to add two attributes to the citation element.
# First, it adds data-ref-id, which is a JSON array of IDs that point
# to the reference(s) that this citation refers to. Second, it adds
# data-ref-html, which is a concatentation of the full references that
# this citations refers to.
#
# Input the HTML document via STDIN and output will be via STDOUT.

require 'rubygems'
require 'bundler/setup'
require 'nokogiri'
require 'json'

html = ARGF.read
html_doc = Nokogiri::HTML(html)

html_doc.css('.citation').each do |citation|
  links = citation.css('a')
  ref_ids = links.map { |l| l['href'] }
  ref_htmls = links.map { |l| html_doc.css(l['href']).inner_html }
  citation['data-ref-id'] = ref_ids.to_json
  citation['data-ref-html'] = ref_htmls.join(" ")
  links.each do |link|
    link.replace(link.content)
  end
end

print html_doc.to_html
